jobs: 
    build:
        name: Hello Wolrd Action
        runs-on: ubuntu-lastest
        steps: 
            - uses: actions/checkout@v1
            - uses: ./action-a
              with:
                MY_NAME: "Mona"